### ISSUE TITLE
problem with semver compare

### ISSUE THREAD

**Issue by michalbagrowski** [k-bx/python-semver#60]
semver is returning error with semver.compare with values:

```>>> semver.parse_version_info("1.9.1-1unms")
VersionInfo(major=1, minor=9, patch=1, prerelease='1unms', build=None)
>>> semver.parse_version_info("1.9.1+1")
VersionInfo(major=1, minor=9, patch=1, prerelease=None, build='1')
>>> semver.compare("1.9.1-1unms","1.9.1+1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/acid/Projects/firmware-update/.virtualenv/lib/python3.6/site-packages/semver.py", line 189, in compare
    return _compare_by_keys(v1, v2)
  File "/Users/acid/Projects/firmware-update/.virtualenv/lib/python3.6/site-packages/semver.py", line 165, in _compare_by_keys
    rccmp = _nat_cmp(rc1, rc2)
  File "/Users/acid/Projects/firmware-update/.virtualenv/lib/python3.6/site-packages/semver.py", line 149, in _nat_cmp
    a_parts, b_parts = split_key(a), split_key(b)
  File "/Users/acid/Projects/firmware-update/.virtualenv/lib/python3.6/site-packages/semver.py", line 136, in split_key
    return [convert(c) for c in key.split('.')]
  File "/Users/acid/Projects/firmware-update/.virtualenv/lib/python3.6/site-packages/semver.py", line 136, in <listcomp>
    return [convert(c) for c in key.split('.')]
  File "/Users/acid/Projects/firmware-update/.virtualenv/lib/python3.6/site-packages/semver.py", line 133, in convert
    return int(text) if re.match('[0-9]+', text) else text
ValueError: invalid literal for int() with base 10: '1unms'
>>>```

**Comment by k-bx** [comment]
@michalbagrowski nice catch, thanks! Care to make a PR with a fix?
